/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as StopwatchRouteImport } from './routes/stopwatch'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const StopwatchRoute = StopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/stopwatch': typeof StopwatchRoute
  '/timer': typeof TimerRoute
}
export interface FileRoutesByTo {
  '/stopwatch': typeof StopwatchRoute
  '/timer': typeof TimerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/stopwatch': typeof StopwatchRoute
  '/timer': typeof TimerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/stopwatch' | '/timer'
  fileRoutesByTo: FileRoutesByTo
  to: '/stopwatch' | '/timer'
  id: '__root__' | '/stopwatch' | '/timer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StopwatchRoute: typeof StopwatchRoute
  TimerRoute: typeof TimerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopwatch': {
      id: '/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  StopwatchRoute: StopwatchRoute,
  TimerRoute: TimerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
